## Results interpretation and model selection

In [1]:
import pandas as pd

In [2]:
results1 = pd.read_csv('data/annresults_32.csv')
results1

,# of Nodes 3,Epochs,Batch size,l2_2,l2_3,Train loss,Test loss,r2
0,32,150,6,0.05,0.00,6.533290,6.560819,-27.203229
1,64,100,6,0.05,0.00,6.533290,6.560819,-27.203229
2,64,100,6,0.03,0.07,6.533290,6.560819,-27.203229
3,64,100,6,0.03,0.05,6.533290,6.560819,-27.203229
4,64,100,6,0.03,0.03,6.533290,6.560819,-27.203229
...,...,...,...,...,...,...,...,...
214,64,50,2,0.07,0.07,0.753138,0.865692,0.228018
215,64,50,2,0.05,0.03,0.719153,0.858226,0.230979
216,64,50,2,0.05,0.05,0.745524,0.858139,0.241578
217,64,50,2,0.03,0.03,0.734300,0.855975,0.244420
218,32,50,2,0.07,0.00,0.730725,0.852876,0.248474

In [3]:
results2 = pd.read_csv('data/annresults_64.csv')
results2

,# of Nodes 3,Epochs,Batch size,l2_2,l2_3,Train loss,Test loss,r2
0,64,50,2,0.03,0.03,0.734300,0.855975,0.244420
1,64,50,2,0.05,0.05,0.745524,0.858139,0.241578
2,64,50,2,0.05,0.03,0.719153,0.858226,0.230979
3,64,50,2,0.03,0.00,0.736160,0.864740,0.221919
4,64,50,2,0.07,0.07,0.753138,0.865692,0.228018
...,...,...,...,...,...,...,...,...
106,64,150,2,0.05,0.05,6.533290,6.560819,-27.203229
107,64,50,4,0.05,0.00,6.533290,6.560819,-27.203229
108,64,50,4,0.03,0.05,6.533290,6.560819,-27.203229
109,64,50,2,0.07,0.03,6.533290,6.560819,-27.203229
110,32,50,2,0.03,0.05,6.533290,6.560819,-27.203229

In [4]:
results3 = pd.read_csv('data/results_nolayer3.csv')
results3.drop(results3.columns[results3.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
results3

,# of Nodes 3,Epochs,Batch size,l2_2,l2_3,Train loss,Test loss,r2
0,0,150,6,0.03,0,0.533064,0.816155,0.258392
1,0,150,2,0.07,0,0.597592,0.817404,0.263103
2,0,150,6,0.05,0,0.547634,0.817605,0.270611
3,0,150,2,0.03,0,0.566058,0.815310,0.271098
4,0,50,6,0.07,0,0.659924,0.824970,0.282134
5,0,100,4,0.07,0,0.584366,0.802526,0.283605
6,0,150,4,0.07,0,0.541711,0.806019,0.287390
7,0,100,2,0.05,0,0.578047,0.800625,0.291886
8,0,150,2,0.05,0,0.550276,0.813433,0.292448
9,0,150,4,0.03,0,0.506330,0.795130,0.293736
10,0,100,4,0.05,0,0.570616,0.796376,0.299433
11,0,150,4,0.05,0,0.535923,0.797589,0.299536
12,0,50,4,0.07,0,0.653393,0.811386,0.300323
13,0,50,2,0.03,0,0.628812,0.803189,0.301080
14,0,100,4,0.03,0,0.552395,0.792972,0.304018
15,0,150,6,0.07,0,0.546207,0.805232,0.306039
16,0,50,2,0.07,0,0.661645,0.796878,0.313576
17,0,100,6,0.05,0,0.552800,0.794471,0.314804
18,0,50,4,0.03,0,0.599245,0.798353,0.316392
19,0,100,2,0.07,0,0.606363,0.794572,0.321231
20,0,50,2,0.05,0,0.640667,0.796567,0.324598
21,0,100,6,0.07,0,0.576384,0.791858,0.325474
22,0,100,2,0.03,0,0.552713,0.777093,0.326436
23,0,50,6,0.03,0,0.587744,0.783185,0.328445
24,0,100,6,0.03,0,0.545614,0.778930,0.329670
25,0,50,4,0.05,0,0.617767,0.793571,0.332049
26,0,50,6,0.05,0,0.600311,0.779136,0.352083

In [7]:
results3.to_csv('data/annresults_0.csv',index = False)